#! /bin/sh
#
# Date   10/04/2014
# Author @avckp aka Abhishek Pandey

# pidprog="sublime_text"
# cmd="subl ."
carrier="photon"
cmd="sudo wvdial $carrier"
pidprog="pppd"
if [ $# -eq 0 ]; then
	echo "[R]un 1/[k]ill 0"
	read todo
	if [ -z $todo ]; then
		echo "Happy Birthday Douchebag!";exit 0
	fi
else 
	todo=$1
fi

case "$todo" in
	1|[rR][uU][nN]*) $cmd ;;
	0|[kK][iI][lL][lL]*) sudo kill -9 `pidof $pidprog` 2>/dev/null;;
	*) echo "Douchebag try run/kill/1/0";exit 0;;
esac

if pidof $pidprog
	then echo "Its there."
else
	echo "Its dead."
fi