#! /bin/sh
#################################################################
# Date   10/04/2014
# Author @avckp aka Abhishek Pandey
# 
# Universal Forfeit License (UFL)
# Pronounced "awful"
# Version 1.1

# Copyright (c) 2014 Abhishek Pandey

# You are permitted to copy and distribute verbatim or modified copies of this
# license. More information at http://geekwagon.net/ufl.

# This license irrevocably grants more rights than possible to the general public
# in any jurisdictions; known and unknown, real and fictional, past and future.
# This is not limited to local government, planet, galaxy, universe, dimension,
# or any other jurisdiction that can exist that has not yet been discovered.

# You can copy, modify, distribute, sublicense, rename, and/or perform the work,
# even for commercial purposes, without asking permission or referencing the 
# original (yes you've been given permission to plagiarise, although you should
# feel bad if you do).

# This work and license is provided without warranty.
#####################################################################

# pidprog="sublime_text"
# cmd="subl ."
carrier="photon"
cmd="sudo wvdial $carrier"
pidprog="pppd"
if [ $# -eq 0 ]; then
	echo "[R]un 1/[k]ill 0"
	read todo
	if [ -z $todo ]; then
		echo "Happy Birthday Douchebag!";exit 0
	fi
else 
	todo=$1
fi

case "$todo" in
	1|[rR][uU][nN]*) $cmd ;;
	0|[kK][iI][lL][lL]*) sudo kill -9 `pidof $pidprog` 2>/dev/null;;
	*) echo "Douchebag try run/kill/1/0";exit 0;;
esac

if pidof $pidprog
	then echo "Its there."
else
	echo "Its dead."
fi